baseURL = "https://usdt2xmr.com/"
languageCode = "en-us"
title = "Buy XMR for USDT"
theme = "PaperMod"

# Enable features
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true

# Security headers
[security]
[security.headers]
Content-Security-Policy = '''
default-src 'self';
script-src 'self' 'unsafe-inline' 'unsafe-eval' https://changenow.io;
style-src 'self' 'unsafe-inline';
img-src 'self' data: https://changenow.io;
frame-src 'self' https://changenow.io;
connect-src 'self' https://changenow.io;
'''

# Build settings
buildDrafts = false
buildFuture = false
buildExpired = false

# Output formats
[outputs]
home = ["HTML", "RSS", "JSON"]

# Theme settings
[params]
keywords = ["$2"]
env = "production"
title = "Buy XMR for USDT"
description = "Buy and sell crypto"
author = "Emma Monday"
copyright = "© 2025 AI Log Lake"
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

# Schema settings
[params.schema]
type = "Organization"
name = "Buy XMR for USDT"
url = "https://usdt2xmr.com/"
logo = "/images/logo.png"
description = "Buy and sell crypto"

[params.homeInfoParams]
Title = "Buy XMR for USDT"
Content = "Buy and sell crypto"
[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 100
threshold = 0.4
useExtendedSearch = false
ignoreLocation = false
ignoreFieldNorm = false
